<?php /* @var $block \Ninetwo\Catalog\Block\Product\View\Productphoto */?>
<?php $recentPhotos = $block->getRecentPhotoForProductView(); ?>
<?php 
	$totalPhoto = $block->getCollectionSize();
	if($totalPhoto >= 1):
?>
<div class="block-title title">
	<strong aria-level="2" role="heading" id="block-related-heading">Customer Photos</strong>
</div>
	<div style="margin-bottom:10px;float:right">
		<a href="<?php echo $block->getViewAllUrl(); ?>" name="view_all" id="view_all" title="View All" class="action submit primary">View All</a>
	</div>
<?php 
	endif;
	foreach($recentPhotos as $recentPhoto):
		?>
	<img style="width:160px;" src="<?php echo $block->getPhotoUrl($recentPhoto->getImage()); ?>" name="photo_immage" id="photo_immage"  alt="<?php echo $recentPhoto->getName(); ?>" title="<?php echo $recentPhoto->getName(); ?>"/>

<?php endforeach; ?>	
